import * as angular from 'angular';
import { HomeController } from './home/Home';
import { AboutController } from './home/About';
import { ContactController } from './home/Contact';
import { CNCData } from './cncdata/CNCData';
import { CNCDataDescription } from './cncdata/CNCDataDescription';
import { CNCDataLeftSide } from './cncdata/CNCDataLeftSide';

import { AligningBallBearings } from './cncdata/list/AligningBallBearings';
import { AligningRollerBearings} from './cncdata/list/AligningRollerBearings';
import { AngularContactBallBearings} from './cncdata/list/AngularContactBallBearings';
import { ArcCylindricalWormGears} from './cncdata/list/ArcCylindricalWormGears';
import { BallLeadingScrewSupportingBearings} from './cncdata/list/BallLeadingScrewSupportingBearings';
import { BWElasticSleevePinCouplings } from './cncdata/list/BWElasticSleevePinCouplings';
import { Cables } from './cncdata/list/Cables';
import { CylindricalRollerBearings } from './cncdata/list/CylindricalRollerBearings';
import { DeepGrooveBallBearings } from './cncdata/list/DeepGrooveBallBearings';
import { DoubleRowCylindricalRollerBearings } from './cncdata/list/DoubleRowCylindricalRollerBearings';
import { DoubleThrustAngularContactBallBearings } from './cncdata/list/DoubleThrustAngularContactBallBearings';
import { ElasticSleevePinCouplings } from './cncdata/list/ElasticSleevePinCouplings';
import { ElectronicSpindleTechParameters } from './cncdata/list/ElectronicSpindleTechParameters';
import { FlangeCouplings } from './cncdata/list/FlangeCouplings';
import { FlexiblePinCouplings } from './cncdata/list/FlexiblePinCouplings';
import { GearCouplings } from './cncdata/list/GearCouplings';
import { HelicalCylindricalGears } from './cncdata/list/HelicalCylindricalGears';
import { HubShapedCouplings } from './cncdata/list/HubShapedCouplings';
import { LinearRollingGuides } from './cncdata/list/LinearRollingGuides';
import { NCSystemFunctionalOptions } from './cncdata/list/NCSystemFunctionalOptions';
import { NCSystemIOUnits } from './cncdata/list/NCSystemIOUnits';
import { NCSystemManuals } from './cncdata/list/NCSystemManuals';
import { NCSystemPowerUnits} from './cncdata/list/NCSystemPowerUnits';

export default function registerControllers(app: angular.IModule): void {
    app.controller('HomeCtrl', HomeController);
    app.controller('AboutCtrl', AboutController);
    app.controller('ContactCtrl', ContactController);
    app.controller('CNCDataCtrl', CNCData);
    app.controller('CncDataLeftSideCtrl', CNCDataLeftSide);
    app.controller('CncDataDescCtrl', CNCDataDescription);

    app.controller('AligningBallBearingCtrl', AligningBallBearings);
    app.controller('AligningRollerBearingsCtrl', AligningRollerBearings);
    app.controller('AngularContactBallBearingsCtrl', AngularContactBallBearings);
    app.controller('ArcCylindricalWormGearsCtrl', ArcCylindricalWormGears);
    app.controller('BallLeadingScrewSupportingBearingsCtrl', BallLeadingScrewSupportingBearings);
    app.controller('BWElasticSleevePinCouplingsCtrl', BWElasticSleevePinCouplings);
    app.controller('CablesCtrl', Cables);
    app.controller('CylindricalRollerBearingsCtrl', CylindricalRollerBearings);
    app.controller('DeepGrooveBallBearingsCtrl', DeepGrooveBallBearings);
    app.controller('DoubleRowCylindricalRollerBearingsCtrl', DoubleRowCylindricalRollerBearings);
    app.controller('DoubleThrustAngularContactBallBearingsCtrl', DoubleThrustAngularContactBallBearings);
    app.controller('ElasticSleevePinCouplingsCtrl', ElasticSleevePinCouplings);
    app.controller('ElectronicSpindleTechParametersCtrl', ElectronicSpindleTechParameters);
    app.controller('FlangeCouplingsCtrl', FlangeCouplings);
    app.controller('FlexiblePinCouplingsCtrl', FlexiblePinCouplings);
    app.controller('GearCouplingsCtrl', GearCouplings);
    app.controller('HelicalCylindricalGearsCtrl', HelicalCylindricalGears);
    app.controller('HubShapedCouplingsCtrl', HubShapedCouplings);
    app.controller('LinearRollingGuidesCtrl', LinearRollingGuides);
    app.controller('NCSystemFunctionalOptionsCtrl', NCSystemFunctionalOptions);
    app.controller('NCSystemIOUnitsCtrl', NCSystemIOUnits);
    app.controller('NCSystemManualsCtrl', NCSystemManuals);
    app.controller('NCSystemPowerUnitsCtrl', NCSystemPowerUnits);
};    
